### ISSUE TITLE
Removal of select options triggers error

### ISSUE THREAD

**Issue by johntell** [Draggable/formeo#102]
How to trigger error:
Add select element -> remove one of the higher options -> Edit label/value for any of the options bellow->
`"Uncaught TypeError: Cannot read property 'label/value' of undefined".
`
The formData show me that the removal of an option will set the option to "null" if done in a wrongful order.

 `"options": [
				{
					"label": "Option 1",
					"value": "option-1",
					"selected": false
				},
				{
					"label": "Option 2",
					"value": "option-2",
					"selected": false
				},
				{
					"label": "Option 3",
					"value": "option-3",
					"selected": false
				},
				{
					"label": "Option 4",
					"value": "option-4",
					"selected": false
				},
				null
			]`

Any suggestions on how this could be fixed? I've spent hours trying to figure it out without no progress, what so ever.

Thanks in advance

**Comment by johntell** [comment]
This bug effects all option based input elements (i.e checkboxes, radio buttons, select options), removing any option will cause this problem and first when you rearange the order of the options, the data will go back to normal. 

Can someone please help me to solve this issue, it's causing data corruption making the data unreadable by the application.

**Comment by kevinchappell** [comment]
Thanks for finding this. I'll look into this today

**Comment by kevinchappell** [comment]
update: working on a fix for this. also related to #105

**Comment by kevinchappell** [comment]
fixed in 1.0-beta
