### ISSUE TITLE
Problem with rendering form

### ISSUE THREAD

**Issue by rjchen2013** [Draggable/formeo#104]
I am trying to render a form created using Formeo but not successful in doing so (Trying to render a form for actual users to use). Here is the script I am using.

    let container = document.querySelector('#formeo-container');
    let renderContainer = document.querySelector('#formeo-editor');
    let formeoOpts = {
        container: container,
        sessionStorage: true
    };

    const formeo = new window.Formeo(formeoOpts, formData);
    formeo.render(renderContainer);

Upon running it, the browser console returns an error 'formeo.render is not a function'.

**Comment by jiehanlin** [comment]
I have the same issue.
Maybe the formeo init is async ,so i using:
window.setTimeout(function ()
{
  formeo.render(renderContainer);
}, 500);

**Comment by rjchen2013** [comment]
@jiehanlin Your solution works. Thank you.
