### ISSUE TITLE
Field label name dissapears when editing field

### ISSUE THREAD

**Issue by eradin** [Draggable/formeo#119]
When pane is closed, label name is present.

![screenshot-2018-5-23 formeo drag drop form creation 1](https://user-images.githubusercontent.com/3924103/40457860-b66cf366-5ead-11e8-90c1-d87701913380.png)

When in edit mode, the label disappears which makes it hard to remember which field you are working on.

![screenshot-2018-5-23 formeo drag drop form creation 2](https://user-images.githubusercontent.com/3924103/40457880-d1b5bab8-5ead-11e8-9b6f-1064153f0087.png)

**Comment by kevinchappell** [comment]
this is no longer the case:
![image](https://user-images.githubusercontent.com/1457540/56075980-fab66d00-5d7f-11e9-84df-4646d8d0f67f.png)
