### ISSUE TITLE
Formeo Fields on toolset disappear when i dragged on toolset to own

### ISSUE THREAD

**Issue by muratsakaaa** [Draggable/formeo#120]
![formeo](https://user-images.githubusercontent.com/38035935/43206416-5c9fb708-902e-11e8-92df-e4bee25aa774.PNG)

**Comment by muratsakaaa** [comment]
I solved thats problem if user drag formcontrol to on own side control was disappeared.I wrote thats code 
  if (e.parentElement.className == "control-group") {

                }  else {
                    return e.parentElement.removeChild(e)
                }  on formeo.min.js  at 431.line (I beautified min.js )

**Comment by kevinchappell** [comment]
Thanks for filing this issue, I'll be sure to add a test case for it.

Glad you worked this out, the next release should have this fixed.

**Comment by eradin** [comment]
Kevin, when do you expect a new release?  It's been a while.

**Comment by kevinchappell** [comment]
Indeed it has been a while. The next release should be in a week or so.

**Comment by kevinchappell** [comment]
This is resolved since 1.0. closing
