### ISSUE TITLE
after removed all options on select and radio elements  can not add new option to these element 

### ISSUE THREAD

**Issue by muratsakaaa** [Draggable/formeo#121]

**Comment by muratsakaaa** [comment]
r.length == 0 ? i = { label: "", selected: false, value: "" } : i = (0, y.cleanObj)(r[r.length - 1]); (at 3922 line)

**Comment by muratsakaaa** [comment]
I solved that issue first of all i defined var i ; at 3916line

**Comment by kevinchappell** [comment]
fixed with 1.0 released, can now remove all and add new
