### ISSUE TITLE
Dragging in Chrome Version 69

### ISSUE THREAD

**Issue by AnasTHH** [Draggable/formeo#134]
Please test it in Chrome Version 69 where it can be dragged after mouse release.
https://i.imgur.com/QZWensD.gif

**Comment by kevinchappell** [comment]
I'm seeing this in Chrome 69 too. What OS are you experiencing this on?

**Comment by AnasTHH** [comment]
Windows 10 Pro x64

**Comment by kevinchappell** [comment]
@AnasTHH Thanks, I have been seeing this on Linux but not Mac OS though its possible the Mac hasn't updated to Chrome 69 yet.

Will work on a fix.

**Comment by markandrewkato** [comment]
Same problem. Working on Mac OSX High Sierra and Mojave, both Chrome v69

**Comment by kevinchappell** [comment]
This is resolved as of 1.0 and Chrome 70+
