### ISSUE TITLE
create form based on formdata

### ISSUE THREAD

**Issue by mallikarjuna009** [Draggable/formeo#145]
i saved formData as json formate. i want to create form based on formdata json saved data. if click button load json and create form showing selected field

**Comment by charmis** [comment]
[Demo source code](https://github.com/Draggable/formeo/blob/master/demo/assets/js/demo.js) has a line
`const formeo = new window.Formeo(formeoOpts);`

You can pass a second parameter to window.Formeo() which is saved form data.

eg: `const formeo = new window.Formeo(formeoOpts, packageJsonFromDB);`

**Comment by thonycc10** [comment]
thank you very much man

**Comment by thonycc10** [comment]
look at this example -> But since I have 2 forms on the same page, when I load data in this way, both forms have the same data.
https://codepen.io/dibwas/pen/yQyaKZ?editors=1111

**Comment by kevinchappell** [comment]
@thonycc10 this is a bug that will be address in the near future. Closing issue since original question was answered
