### ISSUE TITLE
Drag and Drop not working correctly in latest Chrome update

### ISSUE THREAD

**Issue by CapnComic** [Draggable/formeo#146]
Formeo was working perfectly, however my chrome just updated to **Version 69.0.3497.100 (Official Build) (64-bit)** and now when dragging an input in from the menu onto the drop-zone, the 'no-drop' icon stays on the mouse until you release-click the mouse on the drop-zone, then you need to click again to actually drop the item.  Then the item drops into position, however if you happen to have clicked on the dropped item, the input list (on the right) scrolls all the way from 'Common Fields' to the 'Layout' tab.  
Formeo still works as normal on MS-Edge.

**Comment by charmis** [comment]
Duplicate of #134

**Comment by muratsakaaa** [comment]
if you updated last chrome verson problem was solved .I tested.
