### ISSUE TITLE
Trouble finding the required formeo.min.css file

### ISSUE THREAD

**Issue by JaneCoder** [Draggable/formeo#148]
Hello, 

I do not see this file mentioned in the readme in the project. And I have not been able to run the build or start scripts locally to try and create it due to the error: Can't resolve 'mi18n' 

Thanks for any help on how I could get the css file to try out formeo.

**Comment by charmis** [comment]
Can you try 
`npm update mi18n@latest`
Also make sure the folder _formeo\node_modules\mi18n_ has **dist** folder.

**Comment by JaneCoder** [comment]
I do see mi18m under node_modules but it does not have a dist folder. Its package.json starts with  "_from": "mi18n@^0.3.4",
Running the update did not appear to make a difference. 

Here is the first of the "Can't resolve 'mi18n' error:

ERROR in ./src/js/formeo.js
Module not found: Error: Can't resolve 'mi18n' in '/Users/janecoder/testapp/formeo/src/js'
 @ ./src/js/formeo.js 9:13-29
 @ multi (webpack)-dev-server/client?http://localhost:8080 babel-regenerator-runtime ./src/js/formeo.js

**Comment by charmis** [comment]
Can you try 
`npm install mi18n@0.3.4`

**Comment by JaneCoder** [comment]
That worked. Thanks.

**Comment by kevinchappell** [comment]
there are a good number of improvements between `latest` and `0.3.4`. `npm install --save mi18n@latest` should install `0.4.6`.

Apologies for the missing info, it will be updated with the next release.
