### ISSUE TITLE
Formeo Progress

### ISSUE THREAD

**Issue by wgstjf** [Draggable/formeo#15]
Hi,

We are about to start developing a custom plugin that requires a form builder capability.  Formeo looks like it might be the right one for the job but doesn't seem to be quite ready for use yet?  Can you give me any update on when it might be production ready and have documentation available?

Thanks in advance,

Will

**Comment by kevinchappell** [comment]
Hey Will,
At this point I'm not comfortable giving hard dates but can say the project will be very active for the next few months and documentation should be posted this or next week. Development resumed yesterday after a month long break and will be my primary focus for the foreseeable future.

In the meantime feel free to post specific questions or feedback as they arise.

Regards,
Kevin

**Comment by wgstjf** [comment]
Thanks Kevin, that's great news and will keep in touch.

Cheers,

Will
