### ISSUE TITLE
Block elements not editable in 1.0 beta.1

### ISSUE THREAD

**Issue by cpytel** [Draggable/formeo#161]
Hello, using Formeo 1.0 beta.1, I am not able to edit block elements (paragraph and header).

When trying to debug, if I manually set `contenteditable=true` on the element using inspector then I'm able to edit it, and when I save the form and reload the form, whatever I changed it to is in a `value` attribute on the element, but not in the content of the block element.

**Comment by kevinchappell** [comment]
@cpytel Thanks, this is a known bug. Will be resolved in the next release. 👍

**Comment by AlexBreskin** [comment]
This is still not working in the newest release at v1.03 from what I can see (hosted on https://draggable.github.io/formeo/ ), and adding contenteditable as an attribute does not seem to retain the header or paragraph information when saving the form. Is there any way to do this?

**Comment by kevinchappell** [comment]
Yikes, I missed this in the last release. Adding it to the top of my list and will have a fix released this weekend.

**Comment by AlexBreskin** [comment]
> Yikes, I missed this in the last release. Adding it to the top of my list and will have a fix released this weekend.

Any chance we can see this in current round of releases? If it's a simple fix and you can point me to the direction of what needs changing, I can try fixing it myself and making a Pull Request to help out

**Comment by kevinchappell** [comment]
@AlexBreskinRecognite yes- this is long overdue. #196 should finally address this.
