### ISSUE TITLE
Form from formBuilder2Formeo throws an error

### ISSUE THREAD

**Issue by xitara** [Draggable/formeo#167]
I convertet a Form from formBuilder to Formeo and I get the following Error:

`formeo.js?1.0.0:1616 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t.objToStrMap (formeo.js?1.0.0:1616)
    at i (formeo.js?1.0.0:1323)
    at Object.init (formeo.js?1.0.0:1335)
    at new e (formeo.js?1.0.0:3233)
    at 10:606
`

This is the JSON from formBuilder2Formeo:

`let formeoForm = {"id":"05b48988-d179-453f-8c64-8b26d2fd6464","fields":{"c3ad2e7e-25e8-486f-8436-7c256a9cf722":{"id":"c3ad2e7e-25e8-486f-8436-7c256a9cf722","meta":{"id":"text","icon":"text","group":"form"},"attrs":{"required":true,"placeholder":"dein Accountname","className":"form-control cms-fill cms-readonly cms-hidden","name":"username"},"config":{"label":"dein Accountname","helpText":"trage hier deinen Accountnamen ein  wenn dieser nicht bereits vorausgefüllt ist."},"tag":"input"},"2a41603b-ce54-46a6-8f41-a6ea43781f8a":{"id":"2a41603b-ce54-46a6-8f41-a6ea43781f8a","meta":{"id":"text","icon":"text.email","group":"form"},"attrs":{"required":true,"placeholder":"deine E-Mail-Adresse","className":"form-control cms-fill cms-readonly cms-hidden","name":"email"},"config":{"label":"deine E-Mail-Adresse","helpText":"trage hier deine E-Mail-Adresse ein  wenn diese nicht bereits vorausgefüllt ist."},"tag":"email"},"ef079ec2-7b68-464d-96c3-5eea7c6b5241":{"id":"ef079ec2-7b68-464d-96c3-5eea7c6b5241","meta":{"id":"text","icon":"text","group":"form"},"attrs":{"required":true,"placeholder":"dein Videotitel zur Idee","className":"form-control","name":"titel"},"config":{"label":"Videotitel","helpText":"Dein angedachter Videotitel - so könnte das Video heißen."},"tag":"input"},"4e88a833-026b-41fd-bbc7-4a6a9249de4c":{"id":"4e88a833-026b-41fd-bbc7-4a6a9249de4c","meta":{"id":"textarea","icon":"textarea","group":"form"},"attrs":{"required":true,"placeholder":"deine Beschreibung zur Videoidee","className":"form-control","name":"beschreibung","rows":"6"},"config":{"label":"Beschreibung","helpText":"Beschreibe mir hier ausführlich deine Videoidee."},"tag":"textarea"},"befc42ef-2a78-4e6f-bb58-adc9b21bcbba":{"id":"befc42ef-2a78-4e6f-bb58-adc9b21bcbba","meta":{"id":"text","icon":"text","group":"form"},"config":{"label":"Outfitwunsch","helpText":"Trage hier ein mögliches Outfit ein  welches ich tragen könnte."},"attrs":{"placeholder":"dein Outfitwunsch","className":"form-control","name":"outfit"},"tag":"input"},"d28a317d-4ee1-44e4-8593-8fcdb6ee8a20":{"id":"d28a317d-4ee1-44e4-8593-8fcdb6ee8a20","meta":{"id":"button","icon":"button.submit","group":"form"},"config":{"label":"Videoidee einreichen"},"attrs":{"className":"btn btn-success","name":"submit","value":"submit"},"tag":"button","options":{"label":"Submit","value":"submit","type":"submit","className":"btn btn-success"}},"26242e6d-bb44-43af-ab78-b24cba72a2be":{"id":"26242e6d-bb44-43af-ab78-b24cba72a2be","meta":{"id":"hidden","icon":"hidden","group":"form"},"attrs":{"name":"callback","value":"Deine Videoidee wurde erfolgreich übermittelt."},"config":{"label":""},"tag":"input"}},"columns":{"62f13039-893b-427a-ba4f-021e1fdbbb4c":{"id":"62f13039-893b-427a-ba4f-021e1fdbbb4c","children":["c3ad2e7e-25e8-486f-8436-7c256a9cf722"]},"26424a38-85d2-407a-b3d8-4c3e6b8b89e0":{"id":"26424a38-85d2-407a-b3d8-4c3e6b8b89e0","children":["2a41603b-ce54-46a6-8f41-a6ea43781f8a"]},"54a03b23-ac0a-4da7-884c-1a8f17c70dcb":{"id":"54a03b23-ac0a-4da7-884c-1a8f17c70dcb","children":["ef079ec2-7b68-464d-96c3-5eea7c6b5241"]},"b875f9a2-1a3b-4aa8-b63a-bfa7e0a041bf":{"id":"b875f9a2-1a3b-4aa8-b63a-bfa7e0a041bf","children":["4e88a833-026b-41fd-bbc7-4a6a9249de4c"]},"369efdc7-1131-4135-a75d-5c6defd1da5a":{"id":"369efdc7-1131-4135-a75d-5c6defd1da5a","children":["befc42ef-2a78-4e6f-bb58-adc9b21bcbba"]},"2994f98b-2328-4f56-8cd1-b70c5b1d3626":{"id":"2994f98b-2328-4f56-8cd1-b70c5b1d3626","children":["d28a317d-4ee1-44e4-8593-8fcdb6ee8a20"]},"94101378-051d-415d-b7e4-4012557703f1":{"id":"94101378-051d-415d-b7e4-4012557703f1","children":["26242e6d-bb44-43af-ab78-b24cba72a2be"]}},"rows":{"3c631567-8a13-43c0-87d9-3513d1c40f11":{"id":"3c631567-8a13-43c0-87d9-3513d1c40f11","config":{"fieldset":false,"legend":"","inputGroup":false},"attrs":{"className":"f-row"},"children":["62f13039-893b-427a-ba4f-021e1fdbbb4c"]},"ab000cbc-4fad-42dd-b399-49649ec72220":{"id":"ab000cbc-4fad-42dd-b399-49649ec72220","config":{"fieldset":false,"legend":"","inputGroup":false},"attrs":{"className":"f-row"},"children":["26424a38-85d2-407a-b3d8-4c3e6b8b89e0"]},"2a77e244-9c72-41e1-a4a7-693c1acdc4c4":{"id":"2a77e244-9c72-41e1-a4a7-693c1acdc4c4","config":{"fieldset":false,"legend":"","inputGroup":false},"attrs":{"className":"f-row"},"children":["54a03b23-ac0a-4da7-884c-1a8f17c70dcb"]},"4d983add-0b63-46cb-a180-cd213b06862f":{"id":"4d983add-0b63-46cb-a180-cd213b06862f","config":{"fieldset":false,"legend":"","inputGroup":false},"attrs":{"className":"f-row"},"children":["b875f9a2-1a3b-4aa8-b63a-bfa7e0a041bf"]},"049894cb-9210-494c-babf-626067d80ab5":{"id":"049894cb-9210-494c-babf-626067d80ab5","config":{"fieldset":false,"legend":"","inputGroup":false},"attrs":{"className":"f-row"},"children":["369efdc7-1131-4135-a75d-5c6defd1da5a"]},"04933b44-81db-4c02-a333-630f0ae1909d":{"id":"04933b44-81db-4c02-a333-630f0ae1909d","config":{"fieldset":false,"legend":"","inputGroup":false},"attrs":{"className":"f-row"},"children":["2994f98b-2328-4f56-8cd1-b70c5b1d3626"]},"ed0d9ade-df66-4472-8bf6-18879c165f25":{"id":"ed0d9ade-df66-4472-8bf6-18879c165f25","config":{"fieldset":false,"legend":"","inputGroup":false},"attrs":{"className":"f-row"},"children":["94101378-051d-415d-b7e4-4012557703f1"]}},"stages":{"c24a54bb-61c8-49fe-9601-15fb28d0b2a1":{"id":"c24a54bb-61c8-49fe-9601-15fb28d0b2a1","settings":{},"children":["3c631567-8a13-43c0-87d9-3513d1c40f11","ab000cbc-4fad-42dd-b399-49649ec72220","2a77e244-9c72-41e1-a4a7-693c1acdc4c4","4d983add-0b63-46cb-a180-cd213b06862f","049894cb-9210-494c-babf-626067d80ab5","04933b44-81db-4c02-a333-630f0ae1909d","ed0d9ade-df66-4472-8bf6-18879c165f25"]}}};`

And the init:

`let formeoOptions = {
        container: '.formBuilder',
        i18n: {
            location: 'assets/js/formeo-i18n/dist/lang/',
            locale: 'de-DE',
        },
        allowEdit: true,
        events: {
            // onUpdate: console.log,
            onSave: function() {
                console.log(formeo.formData);
            },
        },
    };`

`const formeo = new Formeo(formeoOptions, JSON.stringify(formeoForm));`

EDIT: Sample-Data from https://8zpy130019.codesandbox.io/ throws same error

**Comment by kevinchappell** [comment]
Options are not being correctly generated for `button` type, will open PR now.

also you shouldnt need to stringify `formeoForm` var. 

Edit, [fixed](https://github.com/Draggable/formBuilder2Formeo/pull/1)
