### ISSUE TITLE
Unable to build (current), formeo.min.js breaking (0.7.17)

### ISSUE THREAD

**Issue by AlexBreskin** [Draggable/formeo#171]
Hi there!

I'm trying to get this working on my sails.js application, but I've run into a few problems while trying to get Formeo to work Chrome. It looked like there was a self.navigator declarer instead of window.navigator declarer in the formeo.min.js, which I was able to fix by beautifying the formeo.min.js, debugging it and changing the value out. It's not the most sustainable solution though...

I tried following the instructions on a Windows machine in CONTRIBUTING.md, running the following commands:
`git clone https://github.com/kevinchappell/formeo.git`
`npm install`
`npm run dev`

What doesn't work is `npm run dev` which reports "npm ERR! missing script: dev"

Instead I tried using `npm run prestart` which reports the following:
`> formeo@1.0.0-beta.1 prestart E:\Dev\Recognite\Sandbox\formeo`
`> yarn clean && yarn copy`
``
`yarn run v1.13.0`
`$ rm -rf dist/* demo/assets/formeo*`
`'rm' is not recognized as an internal or external command,`
`operable program or batch file.`
`error Command failed with exit code 1.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! formeo@1.0.0-beta.1 prestart: `yarn clean && yarn copy``
`npm ERR! Exit status 1`
`npm ERR!`
`npm ERR! Failed at the formeo@1.0.0-beta.1 prestart script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

So this looks like a problem with me using windows and powershell, so instead I tried using a Ubuntu 16.04 LTS virtual machine following the same instructions (git clone from kevinchappell/formeo.git as instructed in the documents, but also having no joy in this repo as well)

`npm run dev` again returned with the error "npm ERR! missing script: dev". 

When trying `npm run prestart` I received an error of `sh: 1: yarn: not found`
Alright, so what if I use https://github.com/Draggable/formeo.git as the git clone base while on ubuntu?  I get a lot further into the process, but it fails at npm install with the following at post-install:

`npm WARN prepublish-on-install As of npm@5, ``prepublish`` scripts are deprecated.`
`npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.`
`npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.`
``
`> mini-css-extract-plugin@0.5.0 prepublish /home/recognitedev/Projects/formeo/node_modules/mini-css-extract-plugin`
`> npm run build`
``
``
`> mini-css-extract-plugin@0.5.0 prebuild /home/recognitedev/Projects/formeo/node_modules/mini-css-extract-plugin`
`> npm run clean`
``
``
`> mini-css-extract-plugin@0.5.0 clean /home/recognitedev/Projects/formeo/node_modules/mini-css-extract-plugin`
`> del-cli dist`
``
``
`> mini-css-extract-plugin@0.5.0 build /home/recognitedev/Projects/formeo/node_modules/mini-css-extract-plugin`
`> cross-env NODE_ENV=production babel src -d dist --ignore 'src/**/*.test.js' --copy-files`

`src doesn't exist`
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 2`
`npm ERR! mini-css-extract-plugin@0.5.0 build: ``cross-env NODE_ENV=production babel src -d dist --ignore 'src/**/*.test.js' --copy-files`
`npm ERR! Exit status 2`
`npm ERR! `
`npm ERR! Failed at the mini-css-extract-plugin@0.5.0 build script.`

And this is where I can't progress. There appears to be something happening in the mechanics of mini-css-extract-plugin?

**Comment by abhishekgoenka** [comment]
I am also getting the same error. Did you get any solution?

**Comment by kevinchappell** [comment]
hey guys, this repo is Draggable/formeo not kevinchappell/formeo. i'll push the latest to my fork but the scripts you mentioned are working in the latest on Draggable/formeo.

**Comment by AlexBreskin** [comment]
> 
> 
> hey guys, this repo is Draggable/formeo not kevinchappell/formeo. i'll push the latest to my fork but the scripts you mentioned are working in the latest on Draggable/formeo.

Hi Kevin,

I appreciate that kevinchappell/formeo is not currently in use but the problem I posted about also involves Draggable/formeo for the 2nd half of the issue, which is my attempt at the current Repo.

It appears to be an issue with mini-css-extract-plugin@0.5.0 - is there a way I can progress with this as I'd love to use Formeo and it looks like an excellent platform!

**Comment by AlexBreskin** [comment]
Also, it would be worthwhile to update the contributing.md to reflect the current process to contribute before closing this issue as it's the root cause of the first half of the issue, it would be very helpful for future developers
