### ISSUE TITLE
Can't install formeo

### ISSUE THREAD

**Issue by intelligence0504** [Draggable/formeo#177]
I am gonna build react form builder using formeo.
npx create-react-app my-app
cd my-app
npm i formeo

I have run "npm i formeo"
I got the following issues.

npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! formeo@1.0.0 postinstall: `npm --prefix ./node_modules/mini-css-extract-plugin install ./node_modules/mini-css-extract-plugin && npm run --prefix ./node_modules/mini-css-extract-plugin build`
npm ERR! Exit status 254
npm ERR! 
npm ERR! Failed at the formeo@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2019-03-22T01_17_05_927Z-debug.log

So I have run " yarn add formeo".
But Nothing is displayed.

Help me.

**Comment by kevinchappell** [comment]
fixed in #178 

run `npm i formeo --save` again and should work.

**Comment by intelligence0504** [comment]
Thanks, I have run "npm i formeo --save"
I got other issues.

> TypeError: formeo__WEBPACK_IMPORTED_MODULE_8__.FormeoEditor is not a constructor
App.componentDidMount
src/App.js:23
  20 |         },
  21 |     };
  22 |   // new window.FormeoEditor(options);
> 23 |     const editor = new FormeoEditor()
     | ^  24 | }
  25 | 
  26 | render() {



The full code :
```
`import React, { Component } from 'react';
import './App.css';
import ReactDOM from 'react-dom';
import { FormeoEditor } from 'formeo'


class App extends Component {

  componentDidMount() {
      // require('formeo');

      const options = {
          container: ReactDOM.findDOMNode(this.refs.builder),
          svgSprite: '/assets/img/formeo-sprite.svg',
          i18n: {
              langsDir: '/assets/lang/',
              langs: [
                  'en-US',
              ],
          },
      };
    // new window.FormeoEditor(options);
      const editor = new FormeoEditor()
  }

  render() {
      return (
          <div>
              <div ref="builder" />
          </div>
      );
  }
}
export default App;
```
`

**Comment by kevinchappell** [comment]
It should be ok now. Have a look here: https://codesandbox.io/s/8px8xl8vv9

**Comment by intelligence0504** [comment]
Thx.

**Comment by intelligence0504** [comment]
- would you implement language selection?
https://codesandbox.io/s/ry4753qvvp
- and render from json data

Thanks for your help.
Best Regards.

**Comment by intelligence0504** [comment]
can I implement row and columns functions like formeo in jquery form builder?
