### ISSUE TITLE
Missing files formeo.min.js and formeo.min.css

### ISSUE THREAD

**Issue by phunsanit** [Draggable/formeo#187]
i download formeo with composer  1.8.5 by command 

> composer require draggable/formeo

it not have  formeo.min.js and formeo.min.css in \vendor\draggable\formeo

**Comment by kevinchappell** [comment]
sorry, im not familiar with composer but npm is delivering the files.
![image](https://user-images.githubusercontent.com/1457540/55855285-fab63300-5b1b-11e9-8e2f-a0fb8eda1d1e.png)
 The project has a `composer.json` is anything else needed?

Is composer case sensitive? Maybe `Draggable/formeo`? If you figure it out please open PR
