### ISSUE TITLE
feature request: name-attribute for checkbox

### ISSUE THREAD

**Issue by xitara** [Draggable/formeo#214]
a name-attribute für each checkbox in checkbox-group were fine and a field with single checkbox also.
elements: [] will still ignored in config so I can't do it by myself.

**Comment by xitara** [comment]
done in 1.1.1,  I see

**Comment by kevinchappell** [comment]
@xitara glad you figured it out. as you mentioned 1.1.1 should now have unique names for checkbox groups. More info here: #203
