### ISSUE TITLE
Want to use Formeo with MVC.

### ISSUE THREAD

**Issue by anitas1209** [Draggable/formeo#223]
Want to use Formeo with MVC.

**Comment by detygon** [comment]
Please, clearly explain what you are trying to achieve.

**Comment by xitara** [comment]
I use it in a MVC-Enviroment. Where is your problem?

**Comment by detygon** [comment]
Sorry, I was just trying to help.

**Comment by kevinchappell** [comment]
@mrdionjr , I think @xitara was directing at @anitas1209.

I'm closing due to lack of information. In future we'll have issue templates to guide creation of new issues. 

@anitas1209 feel free to re-open with more info.
