### ISSUE TITLE
FormEo is not rendering in CodePen,Same issue we are getting when we are integrating with MVC application.

### ISSUE THREAD

**Issue by AbhayVermaGit** [Draggable/formeo#224]

**Comment by AbhayVermaGit** [comment]
following is the demo URL what we are getting documentation https://codepen.io/kevinchappell/pen/NAXoRw, There fromeo is not rendering, When we are inspecting browser we found script error in console "Formeo is not defined" , Same issue we are getting when we are integrating it with mvc application .
Following are the code what we are using while integrating in MVC application.

@{
    ViewBag.Title = "Home Page";
 }
<style>
    body {
        background: radial-gradient(circle, #484848, #2F3031);
    }
</style>
<script src="https://draggable.github.io/formeo/assets/js/formeo.min.js"></script>
<link rel="stylesheet" href="https://draggable.github.io/formeo/assets/css/formeo.min.css" />

<div id="formeo-editor"></div>
<script type="text/javascript">
    var formeo = new Formeo({
        container: '#formeo-editor',
        svgSprite: 'https://draggable.github.io/formeo/assets/img/formeo-sprite.svg'
    });
</script>


With above code we are getting error in browser console "Formeo is not defined" , We are unable to identify that region behind the error, so please let us know where we are wrong or there is something missing(updated) in formeo library.

**Comment by xitara** [comment]
You need to load the right ressource in Codepen. 
`https://draggable.github.io/formeo/assets/formeo.min.js`
not exists 'cause /js/ is missing

**Comment by AbhayVermaGit** [comment]
@xitara thanks for your response, but we are getting same issue when we are using in MVC application ,in out code we provided right url of js (formeo.min.js) and we are getting same issue "Formeo is not defined"
we already shared our code what we are using , can you please look at our code, Where we are doing mistake?

**Comment by xitara** [comment]
You have to import FormeoEditor or FormeoRender, i think.

**Comment by AbhayVermaGit** [comment]
@xitara, i am not using this code in react/node/angular project , I am using just only java script and rendering formeo in our(MVC) application so please let us know how to import FormeoEditor or FormeoRender?

**Comment by xitara** [comment]
`var formeo = new FormeoEditor({ ...`
`var formeo = new FormeoRenderer({ ...`

**Comment by AbhayVermaGit** [comment]
@xitara, please check attached screen shot ,we imported  FormeoEditor we did not getting any error in browser console , but Form is not rendering, we are getting only horizontal line, if you have any sample code, please send us by which we can render fromeo. 

![FormeoEditor](https://user-images.githubusercontent.com/50825466/59606917-e3a14c00-912f-11e9-9393-88f7876f242f.png)

**Comment by xitara** [comment]
use editorContainer instead of container

**Comment by AbhayVermaGit** [comment]
@xitara Thanks for your support, Now it's working fine.

**Comment by kevinchappell** [comment]
@xitara thank you! I will update the codepen.io

**Comment by santigolucass** [comment]
@xitara GOAT
