### ISSUE TITLE
Unable to render form designed by formeo and also not able to get html of designed form.   

### ISSUE THREAD

**Issue by AbhayVermaGit** [Draggable/formeo#225]
`Following are the code what we are trying to render designed form in a div “formeo-render” on button click “btnRenderForm”, Form is not rendered we are getting error “u.container.appendChild is not a function” in browser console, `

**`<script src="https://draggable.github.io/formeo/assets/js/formeo.min.js"></script>
<link rel="stylesheet" href="https://draggable.github.io/formeo/assets/css/formeo.min.css" />

<div id="formeo-editor"></div>
<div id="formeo-render"></div>

<button class="btn btn-info" id="btnRenderForm" onclick="FormRender();">RenderForm</button>

<script type="text/javascript">
    var formeo = new FormeoEditor({
        editorContainer: '#formeo-editor',
        svgSprite: 'https://draggable.github.io/formeo/assets/img/formeo-sprite.svg'
    });
    var renderedForm = new FormeoRenderer({
        renderContainer: '#formeo-render',
    });
    function FormRender() {
        renderedForm.render(formeo.formData);
    }
 </script>

`**
Someone please go through our code and let us know what are missing, if someone have code sample to render form and get html of designed form  please share that

**Comment by xitara** [comment]
what's about debugging, for example

`console.log(formeo.formData);`

in FormRender()?

**Comment by AbhayVermaGit** [comment]
@xitara , Thanks for your response, following are attached screen shot of  console.log(formeo.formData); 

![Formeo-render1](https://user-images.githubusercontent.com/50825466/59783144-1dfc1c00-92dd-11e9-911f-b5ff134d7787.PNG)
![Formeo-render](https://user-images.githubusercontent.com/50825466/59783153-22283980-92dd-11e9-89a7-8eb260d56d89.PNG)

**Comment by xitara** [comment]
ok, I looked into my own code. renderContainer needs an element, not a selector. try 

`renderContainer: document.querySelector('#formeo-render'), `

this could be the problem

**Comment by AbhayVermaGit** [comment]
Thanks you @xitara , it's working fine and now i am able to get html of rendered form.

**Comment by kevinchappell** [comment]
@xitara Thank you for identifying this bug. PR opened #226
