### ISSUE TITLE
How do I use formeo in my project manually, without npm?

### ISSUE THREAD

**Issue by Mareenag** [Draggable/formeo#248]
I have followed documentation given here but it is not works for me. Can anyone guide me please.?

**Comment by marcus-at-localhost** [comment]
Can you setup a jsfiddle.net to show what you have tried?

**Comment by Mareenag** [comment]
Thanks for your reply @marcus-at-localhost . I had some JS file conflicts on my system. I fixed, now it works fine.
Thank you.

**Comment by marcus-at-localhost** [comment]
@Mareenag glad you figured it out. Please close the ticket in that case. Thanks!
