### ISSUE TITLE
Input event on Select options is causing input focus loss after each keypress 

### ISSUE THREAD

**Issue by DivineLawnmower** [Draggable/formeo#291]
Something has changed recently which means that the input event on Select control Options is causing the input box to lose focus after each character is input.

I am currently using formeo via:
   <script src="https://draggable.github.io/formeo/assets/js/formeo.min.js"></script>

Please see video for details:
https://i.gyazo.com/23d2607ca2a1bbb191b4cc4528e17408.mp4

Better video:
https://i.gyazo.com/5d3a8f7b15a5981870e7316e6946fd7b.mp4

Once you remove the event from the input this issue stops occurring, however I am not sure of the consequences of removing this event.

Is it possible that the form is re-rendering each time?

Any assistance is appreciated.

**Comment by kevinchappell** [comment]
@DivineLawnmower thanks for opening this issue. it does seem the input is re-rendering. i'll look into what changed there.

**Comment by hackontech** [comment]
Any update on this?

**Comment by Sathieswar** [comment]
This issue is occurring for Radio and Checkbox Control as well

**Comment by rezahmady** [comment]
Please fix this bug as soon as possible

**Comment by kevinchappell** [comment]
sorry for the delay, this should be fixed now

**Comment by rezahmady** [comment]
thank you very much
@kevinchappell
