### ISSUE TITLE
window.JSON.stringify($(fbRender).formRender("userData"))???

### ISSUE THREAD

**Issue by yoshie902a** [Draggable/formeo#298]
After reviewing https://formbuilder.online/docs/formRender/actions/userData/

In Form Builder you can use the below code to get the form and data merged together to store in database.

      `window.alert(window.JSON.stringify($(fbRender).formRender("userData")));`

 However, it does not work with Formeo. What is the formeo way of doing this?

**Comment by kevinchappell** [comment]
the formeo renderer builds semantic form inputs so this should be possible using the built-in FormData. https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_FormData_Objects
