### ISSUE TITLE
Panels are resized to huge height 

### ISSUE THREAD

**Issue by robert-haynes** [Draggable/formeo#305]
I have used the latest drop and when I construct the editor using:

 editor = new window.FormeoEditor({
      editorContainer: '#formeo-editor1',
      debug: true,
      svgSprite: 'https://draggable.github.io/formeo/assets/img/formeo-sprite.svg'
   },{});

The panels inside the div are huge - in fact often 5000px high and sometimes up to 50000px high. I have tried to set max-height on the owning objects and also used a setTimeout(1000) to resize the panels - but if you click on the panes then they get resized automatically. I note the height is set on the elements with class panels somehow:

![Screen Shot 2021-01-27 at 16 47 37](https://user-images.githubusercontent.com/55533833/106016096-6980c980-60bf-11eb-8350-acfc9a8f9269.png)

![Screen Shot 2021-01-27 at 16 49 29](https://user-images.githubusercontent.com/55533833/106016353-ac42a180-60bf-11eb-964e-fb2de75f64dc.png)

**Comment by kevinchappell** [comment]
oof, i wish i saw this one. that said I am not able to reproduce this issue in the current versions.

**Comment by andrew-m-p** [comment]
> oof, i wish i saw this one. that said I am not able to reproduce this issue in the current versions.

Hello, I'm seeing the same problem, I presume you are calculating heights somewhere in js ,can you point me where please. See diagram , even though I set .build-forms height I get crazy heights being set on the children. Any help appriciated. Thanks

<img width="1654" height="192" alt="Image" src="https://github.com/user-attachments/assets/3ddd0e1d-4712-4e67-b15d-4134d2cbbc6f" />
