### ISSUE TITLE
custom attrs dont show label on edit

### ISSUE THREAD

**Issue by argus-cs** [Draggable/formeo#307]
several custom attributes just show the value, making it difficult to identify them
![image](https://user-images.githubusercontent.com/8759877/113722426-c9e74500-96c6-11eb-9d64-3729944feee8.png)

**Comment by dougauerbach** [comment]
I agree, this appears to be a bug.
The name of the custom attribute will appear in the placeholder. This is not helpful if there is a non-blank value in that custom attribute, however.

**Comment by Iuliia21** [comment]
It's due to the translation. II added an attribute via config file and I got the same issue (it works correctly if using  btn '+Attribute'). Adding the translation solved this problem for my  project :)

**Comment by dougauerbach** [comment]
When I use the +Attribute button, any custom attributes are not rendered as labels, but rather as placeholders. Thus they are not displayed if a non-blank attribute value is supplied.

**Comment by kevinchappell** [comment]
This is fixed in more recent versions: 
![image](https://github.com/user-attachments/assets/cb2228ba-dd91-404c-a154-8c5e0f6a2c0b)
