### ISSUE TITLE
Formeo Conditions

### ISSUE THREAD

**Issue by Etepeus** [Draggable/formeo#310]
When creating conditions the value field only allows one word and does not allow spaces - can this be changed/fixed.
Also when you create a condition and then use the option to Make this row and input group the conditions only works on line one not on any added line
The attachment outline the issue and how we have tried to use conditions.
[Bugs in Form Builder.docx](https://github.com/Draggable/formeo/files/6837635/Bugs.in.Form.Builder.docx)

**Comment by kevinchappell** [comment]
Thank you for putting together this document. I will begin working on the first bug, put will need to put some thought into the conditions for input group rows before starting.
