### ISSUE TITLE
Intregration into WordPress plugin

### ISSUE THREAD

**Issue by wgstjf** [Draggable/formeo#32]
Hi,

I am looking to integrate Formeo into a plugin we are building for a client.  The builder will be in the admin area with the rendering of the form visible to frontend users.

I have enqueued the required scripts and have the form builder visible in the admin area but whenever I click on any Formeo buttons (such as edit field etc) the page reloads....any idea what is causing this?

Thanks in advance,

Will

**Comment by kevinchappell** [comment]
Hey Will, 
This is a bug I will address today. Thank you for catching this. 

Kevin

**Comment by wgstjf** [comment]
That's great Kevin, thanks!
