### ISSUE TITLE
Formeo Date & Number elements

### ISSUE THREAD

**Issue by satishjes** [Draggable/formeo#343]
For Date element, attr "current_date_as_default" is not working and the element does not show system date on preview.
For Number element, there is no provision to set number of decimal places, numbers are set to 3 decimal places by default.
Conditional fields also cannot be enabled as conditions tab is missing.

**Comment by kevinchappell** [comment]
sorry but what is `current_date_as_default` and what is the expected behavior? it sounds like youre talking about a custom number input, the editor ships with the standard `<input type="number/>"`
