### ISSUE TITLE
TypeError: t is undefined

### ISSUE THREAD

**Issue by giannicolac** [Draggable/formeo#350]
Hello, i'm using vue 2, and i have been trying to make formeo work with it to no avail, i get the error "TypeError: t is undefined". I'm not sure what i'm doing wrong. My current code is this:

<template>
  <div class="formeo-wrap"></div>
</template>

<script>
import { FormeoEditor } from 'formeo';

export default {
  mounted() {
    const editor = new FormeoEditor()  
    }
}
</script>

I expect to see the editor, but instead i get the error.

**Comment by kevinchappell** [comment]
can you create a minimal reproduction of the issue using codesandbox or similar online editor?
