### ISSUE TITLE
`onUpdate` does not get triggered properly

### ISSUE THREAD

**Issue by derrandz** [Draggable/formeo#38]
The `onUpdate` event does not get triggered when a new element is dropped on the stage unless you add then delete an element.

This bug is replicated in this [codepen](http://codepen.io/anon/pen/WGraNa)

**Comment by tnory56** [comment]
FF 49.0.2 Works and logs to console as expected.

**Comment by kevinchappell** [comment]
@tnory56 :+1:

**Comment by onyekaa** [comment]
This does not work for me anymore either. I updated the JS yesterday, for the first time since December and the `onUpdate` event no longer fires.
