### ISSUE TITLE
Last update editor disappears and appears in dynamic editing.

### ISSUE THREAD

**Issue by georgedevphp** [Draggable/formeo#382]
After the update to the new version, the editor does not work dynamically with ajax, but it has to be set with a fixed value.
I need to pass the JSON from the api.

Please analyze and review my code so that you can replicate the error, to see what the error is.

On localhost, you have to reload the page several times until it appears, but on the hosting it does not appear at all, at least after 30 attempts.

[https://codepen.io/JordanGarciaDev/pen/jENOVQw](https://codepen.io/JordanGarciaDev/pen/jENOVQw)

**Comment by kevinchappell** [comment]
#385 and #384 should have the fixes needed and the codepen now loads:
![image](https://github.com/user-attachments/assets/a37131da-da85-45f0-9b9d-ee8e6eaa5a55)
