### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by andrea-dellepiane** [Draggable/formeo#386]
Trying to build from cloned repo I get:
 ERROR  error during build:                                                                                                                                                         20:43:43  
[vite-plugin-static-copy:build] No file was found to copy on C:\repos\git\formeo\src\lib\icons\formeo-sprite.svg src.
    at collectCopyTargets (file:///C:/repos/git/formeo/node_modules/vite-plugin-static-copy/dist/index.js:512:13)
    at async copyAll (file:///C:/repos/git/formeo/node_modules/vite-plugin-static-copy/dist/index.js:577:23)
    at async Object.writeBundle (file:///C:/repos/git/formeo/node_modules/vite-plugin-static-copy/dist/index.js:1105:22)
    at async Promise.all (index 1)
    at async PluginDriver.hookParallel (file:///C:/repos/git/formeo/node_modules/rollup/dist/es/shared/node-entry.js:21127:9)
    at async file:///C:/repos/git/formeo/node_modules/rollup/dist/es/shared/node-entry.js:22170:13
    at async catchUnfinishedHookActions (file:///C:/repos/git/formeo/node_modules/rollup/dist/es/shared/node-entry.js:21545:16)
    at async build (file:///C:/repos/git/formeo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65449:16)
    at async CAC.<anonymous> (file:///C:/repos/git/formeo/node_modules/vite/dist/node/cli.js:828:5)

But the file C:\repos\git\formeo\src\lib\icons\formeo-sprite.svg is there... 
Any suggestion?

**Comment by kevinchappell** [comment]
Can you describe a bit more of the steps to replicate the problem and ~your computer OS~ nevermind, I see it's Windows. I suspect it may have to do with path resolution on a Windows machine but I don't have one to test.

I will try to replicate the problem and see what's happening

**Comment by andrea-dellepiane** [comment]
I just cloned the repo in a folder (C:\repos\git\) cd in the formeo dir and called npm install and npm run build.
Here you can find the commands I issued and the output (did it all as administrator in order to overcome security issues that may arise):
c:\repos\git>git clone https://github.com/Draggable/formeo.git
Cloning into 'formeo'...
remote: Enumerating objects: 5705, done.
remote: Counting objects: 100% (1525/1525), done.
remote: Compressing objects: 100% (779/779), done.
remote: Total 5705 (delta 801), reused 1366 (delta 724), pack-reused 4180 (from 1)
Receiving objects: 100% (5705/5705), 11.01 MiB | 8.36 MiB/s, done.
Resolving deltas: 100% (3263/3263), done.

c:\repos\git>cd formeo

c:\repos\git\formeo>npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead

> formeo@3.1.0 prepare
> lefthook install

sync hooks: ✔️ (commit-msg, pre-push)

added 689 packages, and audited 932 packages in 9s

187 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

c:\repos\git\formeo>npm run build

> formeo@3.1.0 prebuild
> npm run build:lib


> formeo@3.1.0 build:lib
> vite build --config vite.config.lib.mjs

vite v5.4.11 building for production...
✓ 334 modules transformed.
dist/formeo.min.css   43.87 kB │ gzip:  7.37 kB
dist/formeo.es.js    342.53 kB │ gzip: 82.11 kB
dist/formeo.min.css   43.87 kB │ gzip:  7.37 kB
dist/formeo.cjs.js   146.92 kB │ gzip: 47.47 kB
dist/formeo.min.css   43.87 kB │ gzip:  7.37 kB
dist/formeo.umd.js   147.16 kB │ gzip: 47.57 kB
✓ built in 2.65s

> formeo@3.1.0 build
> npm-run-all -p build:icons build:demo


> formeo@3.1.0 build:demo
> vite build --mode demo


> formeo@3.1.0 build:icons
> node ./tools/generate-sprite

vite v5.4.11 building for demo...                                                                             14:50:18
✓ 385 modules transformed.                                                                                    14:50:19

 ERROR  x Build failed in 4.26s                                                                               14:50:22

../../dist/demo/index.html                                     3.31 kB │ gzip:   1.52 kB                      14:50:22
../../dist/demo/assets/img/github.png                          4.11 kB                                        14:50:22
../../dist/demo/assets/js/theme-github_light_default.min.js    4.76 kB                                        14:50:22
../../dist/demo/assets/img/formeo-logo.svg                    10.33 kB │ gzip:   4.65 kB                      14:50:22
../../dist/demo/assets/js/mode-json.min.js                    10.48 kB                                        14:50:22
../../dist/demo/assets/css/demo.min.css                       47.21 kB │ gzip:   8.18 kB                      14:50:22
../../dist/demo/assets/js/demo.min.js                        612.02 kB │ gzip: 175.18 kB                      14:50:22

 WARN                                                                                                         14:50:22
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

                                                                                                              14:50:22
✨ [vite-plugin-compression]:algorithm=gzip - compressed file successfully:
demo/assets/js/mode-json.min.js.gz   10.33kb / gzip: 2.45kb                                                   14:50:22
demo/assets/css/demo.min.css.gz      46.19kb / gzip: 7.99kb                                                   14:50:22
demo/assets/js/demo.min.js.gz        597.98kb / gzip: 170.53kb                                                14:50:22
                                                                                                              14:50:22


 **ERROR  error during build:                                                                                   14:50:22
[vite-plugin-static-copy:build] No file was found to copy on c:\repos\git\formeo\src\lib\icons\formeo-sprite.svg src.
    at collectCopyTargets (file:///c:/repos/git/formeo/node_modules/vite-plugin-static-copy/dist/index.js:512:13)
    at async copyAll (file:///c:/repos/git/formeo/node_modules/vite-plugin-static-copy/dist/index.js:577:23)
    at async Object.writeBundle (file:///c:/repos/git/formeo/node_modules/vite-plugin-static-copy/dist/index.js:1105:22)
    at async Promise.all (index 1)
    at async PluginDriver.hookParallel (file:///c:/repos/git/formeo/node_modules/rollup/dist/es/shared/node-entry.js:21127:9)
    at async file:///c:/repos/git/formeo/node_modules/rollup/dist/es/shared/node-entry.js:22170:13
    at async catchUnfinishedHookActions (file:///c:/repos/git/formeo/node_modules/rollup/dist/es/shared/node-entry.js:21545:16)
    at async build (file:///c:/repos/git/formeo/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65449:16)
    at async CAC.<anonymous> (file:///c:/repos/git/formeo/node_modules/vite/dist/node/cli.js:828:5)**

ERROR: "build:demo" exited with 1.

Obviusly if I open this  c:\repos\git\formeo\src\lib\icons\formeo-sprite.svg the file exists and can be open


Thanks in advance for your help

**Comment by JordanGarciaDev** [comment]
![image](https://github.com/user-attachments/assets/2c41bf35-afc9-49ec-be07-9028d1192242)

Error rendering textarea values:

Data test example:

{
  "id": "f6c6ebaf-5923-48d4-bea6-27afbcb9c0ce",
  "stages": {
    "f3f9328c-f022-453b-bddb-f1b5905d9010": {
      "children": [
        "319b03c3-1d8d-4f45-973c-244800b3f5ab",
        "985a993d-aca8-4bf7-a687-bddf70ed0c5b",
        "43a992f6-342b-4a89-a3b5-43b0bbd72229"
      ],
      "id": "f3f9328c-f022-453b-bddb-f1b5905d9010"
    }
  },
  "rows": {
    "319b03c3-1d8d-4f45-973c-244800b3f5ab": {
      "config": {
        "fieldset": false,
        "legend": "",
        "inputGroup": false
      },
      "children": [
        "a37b80e0-8f24-49d5-bd67-0f897558e9d0"
      ],
      "className": [
        "formeo-row"
      ],
      "id": "319b03c3-1d8d-4f45-973c-244800b3f5ab"
    },
    "985a993d-aca8-4bf7-a687-bddf70ed0c5b": {
      "config": {
        "fieldset": false,
        "legend": "",
        "inputGroup": false
      },
      "children": [
        "121ba22e-7da9-4b25-b77c-0c8882866006"
      ],
      "className": [
        "formeo-row"
      ],
      "id": "985a993d-aca8-4bf7-a687-bddf70ed0c5b"
    },
    "43a992f6-342b-4a89-a3b5-43b0bbd72229": {
      "config": {
        "fieldset": false,
        "legend": "",
        "inputGroup": false
      },
      "children": [
        "7ba8089a-91eb-4bf4-b020-b1d1f1964c51"
      ],
      "className": [
        "formeo-row"
      ],
      "id": "43a992f6-342b-4a89-a3b5-43b0bbd72229"
    }
  },
  "columns": {
    "a37b80e0-8f24-49d5-bd67-0f897558e9d0": {
      "config": {
        "width": "100%"
      },
      "children": [
        "2f521f05-2b42-40c8-a333-bfe8bf1c3e79"
      ],
      "className": [
        "formeo-column"
      ],
      "id": "a37b80e0-8f24-49d5-bd67-0f897558e9d0"
    },
    "121ba22e-7da9-4b25-b77c-0c8882866006": {
      "config": {
        "width": "100%"
      },
      "children": [
        "8423432e-ec7f-4bfb-aeb0-0767b81b8262"
      ],
      "className": [
        "formeo-column"
      ],
      "id": "121ba22e-7da9-4b25-b77c-0c8882866006"
    },
    "7ba8089a-91eb-4bf4-b020-b1d1f1964c51": {
      "config": {
        "width": "100%"
      },
      "children": [
        "0bbb9ebe-ac86-4326-8400-7fd1f86d8db9"
      ],
      "className": [
        "formeo-column"
      ],
      "id": "7ba8089a-91eb-4bf4-b020-b1d1f1964c51"
    }
  },
  "fields": {
    "2f521f05-2b42-40c8-a333-bfe8bf1c3e79": {
      "tag": "h1",
      "attrs": {
        "tag": [
          {
            "label": "H1",
            "value": "h1",
            "selected": true
          },
          {
            "label": "H2",
            "value": "h2",
            "selected": false
          },
          {
            "label": "H3",
            "value": "h3",
            "selected": false
          },
          {
            "label": "H4",
            "value": "h4",
            "selected": false
          }
        ],
        "className": ""
      },
      "config": {
        "label": "Encabezamiento",
        "hideLabel": true,
        "editableContent": true,
        "controlId": "html.header"
      },
      "content": "<span style=\"font-family: Inter, &quot;Helvetica Neue&quot;, Arial, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;\">Entrevista&nbsp;</span>",
      "action": [],
      "id": "2f521f05-2b42-40c8-a333-bfe8bf1c3e79"
    },
    "8423432e-ec7f-4bfb-aeb0-0767b81b8262": {
      "tag": "textarea",
      "config": {
        "label": "<span style=\"font-family: Inter, &quot;Helvetica Neue&quot;, Arial, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;\">1. ¿Por qué te interesa formar parte de nuestro equipo en Dental OralCare?</span>",
        "controlId": "textarea"
      },
      "attrs": {
        "required": false,
        "value": "sss"
      },
      "id": "8423432e-ec7f-4bfb-aeb0-0767b81b8262",
      "content": ""
    },
    "0bbb9ebe-ac86-4326-8400-7fd1f86d8db9": {
      "tag": "input",
      "attrs": {
        "required": false,
        "type": "text",
        "className": "",
        "value": "jaider"
      },
      "config": {
        "label": "Text Input",
        "controlId": "text-input"
      },
      "id": "0bbb9ebe-ac86-4326-8400-7fd1f86d8db9"
    }
  }
}

**Comment by kevinchappell** [comment]
> I just cloned the repo in a folder (C:\repos\git) cd in the formeo dir and called npm install and npm run build. Here you can find the commands I issued and the output (did it all as administrator in order to overcome security issues that may arise): c:\repos\git>git clone https://github.com/Draggable/formeo.git Cloning into 'formeo'... remote: Enumerating objects: 5705, done. remote: Counting objects: 100% (1525/1525), done. remote: Compressing objects: 100% (779/779), done. remote: Total 5705 (delta 801), reused 1366 (delta 724), pack-reused 4180 (from 1) Receiving objects: 100% (5705/5705), 11.01 MiB | 8.36 MiB/s, done. Resolving deltas: 100% (3263/3263), done.

@andrea-dellepiane Thanks for following up with this detailed explanation. I finally got my hands on a windows PC and will be working on this issue this weekend. Thank you for your patience.
