### ISSUE TITLE
textarea value not rendered

### ISSUE THREAD

**Issue by kevinchappell** [Draggable/formeo#388]
![image](https://github.com/user-attachments/assets/2c41bf35-afc9-49ec-be07-9028d1192242)

Error rendering textarea values:

Data test example:

{
  "id": "f6c6ebaf-5923-48d4-bea6-27afbcb9c0ce",
  "stages": {
    "f3f9328c-f022-453b-bddb-f1b5905d9010": {
      "children": [
        "319b03c3-1d8d-4f45-973c-244800b3f5ab",
        "985a993d-aca8-4bf7-a687-bddf70ed0c5b",
        "43a992f6-342b-4a89-a3b5-43b0bbd72229"
      ],
      "id": "f3f9328c-f022-453b-bddb-f1b5905d9010"
    }
  },
  "rows": {
    "319b03c3-1d8d-4f45-973c-244800b3f5ab": {
      "config": {
        "fieldset": false,
        "legend": "",
        "inputGroup": false
      },
      "children": [
        "a37b80e0-8f24-49d5-bd67-0f897558e9d0"
      ],
      "className": [
        "formeo-row"
      ],
      "id": "319b03c3-1d8d-4f45-973c-244800b3f5ab"
    },
    "985a993d-aca8-4bf7-a687-bddf70ed0c5b": {
      "config": {
        "fieldset": false,
        "legend": "",
        "inputGroup": false
      },
      "children": [
        "121ba22e-7da9-4b25-b77c-0c8882866006"
      ],
      "className": [
        "formeo-row"
      ],
      "id": "985a993d-aca8-4bf7-a687-bddf70ed0c5b"
    },
    "43a992f6-342b-4a89-a3b5-43b0bbd72229": {
      "config": {
        "fieldset": false,
        "legend": "",
        "inputGroup": false
      },
      "children": [
        "7ba8089a-91eb-4bf4-b020-b1d1f1964c51"
      ],
      "className": [
        "formeo-row"
      ],
      "id": "43a992f6-342b-4a89-a3b5-43b0bbd72229"
    }
  },
  "columns": {
    "a37b80e0-8f24-49d5-bd67-0f897558e9d0": {
      "config": {
        "width": "100%"
      },
      "children": [
        "2f521f05-2b42-40c8-a333-bfe8bf1c3e79"
      ],
      "className": [
        "formeo-column"
      ],
      "id": "a37b80e0-8f24-49d5-bd67-0f897558e9d0"
    },
    "121ba22e-7da9-4b25-b77c-0c8882866006": {
      "config": {
        "width": "100%"
      },
      "children": [
        "8423432e-ec7f-4bfb-aeb0-0767b81b8262"
      ],
      "className": [
        "formeo-column"
      ],
      "id": "121ba22e-7da9-4b25-b77c-0c8882866006"
    },
    "7ba8089a-91eb-4bf4-b020-b1d1f1964c51": {
      "config": {
        "width": "100%"
      },
      "children": [
        "0bbb9ebe-ac86-4326-8400-7fd1f86d8db9"
      ],
      "className": [
        "formeo-column"
      ],
      "id": "7ba8089a-91eb-4bf4-b020-b1d1f1964c51"
    }
  },
  "fields": {
    "2f521f05-2b42-40c8-a333-bfe8bf1c3e79": {
      "tag": "h1",
      "attrs": {
        "tag": [
          {
            "label": "H1",
            "value": "h1",
            "selected": true
          },
          {
            "label": "H2",
            "value": "h2",
            "selected": false
          },
          {
            "label": "H3",
            "value": "h3",
            "selected": false
          },
          {
            "label": "H4",
            "value": "h4",
            "selected": false
          }
        ],
        "className": ""
      },
      "config": {
        "label": "Encabezamiento",
        "hideLabel": true,
        "editableContent": true,
        "controlId": "html.header"
      },
      "content": "<span style=\"font-family: Inter, &quot;Helvetica Neue&quot;, Arial, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;\">Entrevista&nbsp;</span>",
      "action": [],
      "id": "2f521f05-2b42-40c8-a333-bfe8bf1c3e79"
    },
    "8423432e-ec7f-4bfb-aeb0-0767b81b8262": {
      "tag": "textarea",
      "config": {
        "label": "<span style=\"font-family: Inter, &quot;Helvetica Neue&quot;, Arial, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;\">1. ¿Por qué te interesa formar parte de nuestro equipo en Dental OralCare?</span>",
        "controlId": "textarea"
      },
      "attrs": {
        "required": false,
        "value": "sss"
      },
      "id": "8423432e-ec7f-4bfb-aeb0-0767b81b8262",
      "content": ""
    },
    "0bbb9ebe-ac86-4326-8400-7fd1f86d8db9": {
      "tag": "input",
      "attrs": {
        "required": false,
        "type": "text",
        "className": "",
        "value": "jaider"
      },
      "config": {
        "label": "Text Input",
        "controlId": "text-input"
      },
      "id": "0bbb9ebe-ac86-4326-8400-7fd1f86d8db9"
    }
  }
}

_Originally posted by @JordanGarciaDev in https://github.com/Draggable/formeo/issues/386#issuecomment-2543174262_

**Comment by Orlandomrqez** [comment]
I also have the same error when trying to render the value stored in the textarea of ​​a form created with formeo, the other inputs do grab the attr value, but the textarea does not.
When will it be fixed?
![Test](https://github.com/user-attachments/assets/3dcd284c-5f85-45cb-899b-5d32f401fd22)

**Comment by georgedevphp** [comment]
![image](https://github.com/user-attachments/assets/d0edf2ad-d774-4307-bea5-e63419b3edca)

I have the same error, the values ​​received by textarea are not rendered in https://draggable.github.io/formeo/ or in my project.

When editing the form, the value of some inputs is also lost.
