### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by eradin** [Draggable/formeo#47]
Kevin, soem feedback.  I've periodically played with the demo and I just can't seem to create columns.  And when I do, it's just plain luck.  Personally, I don't find the columns intuitive.  Is it still a work in progress?  My suggestion is to rework it so it's obvious how to drop a control onto a column.  Perhaps a landing zone on either side of a row.

**Comment by eradin** [comment]
Update.  Ok, I figured it out.  Still not intuitive to me. I was trying to drag a field to a column without first dropping it on a row (then moving to a column).  I believe most people will want to drag and drop to a column, not drag, drop and move to a column.  I think it makes more sense to drag and drop on the left or right edge of a field.  Just like we insert a row by dragging to the top or bottom of a row.

FYI, I plan on providing this plugin on our web site for end users to create simple custom forms.  90% of these users are non technical so super simple instructions are required.  The current formbuilder does not support columns so this would be a huge improvement, if it's easy to understand.  My goal here is to provide constructive feedback not to be critical.

**Comment by kevinchappell** [comment]
@eradin I couldn't agree more that the columns feature needs reworking. Future versions will allow dropping columns and layout templates from the control bar.

Thanks for your input, it's really appreciated.
