### ISSUE TITLE
values for fields other than text not sent

### ISSUE THREAD

**Issue by jvm985** [Draggable/formeo#49]
Hi ,
in the onSave event I json all formData to the server. This works fine, but it seems that only the values of text fields are being sent. Other field types have no 'value' index in field->attrs[].

Joachim

**Comment by kevinchappell** [comment]
@jvm985 could you share a config or create a jsfiddle so that I may test? Are you saying only text inputs are included in the response from the onSave event?

**Comment by jvm985** [comment]
Exactly. I'll create a fiddle asap.

**Comment by jvm985** [comment]
https://jsfiddle.net/jvm985/tkof5smc/

to reproduce: create a text and a textarea. onSave, in the console the formData object contains rows->columns->fields->attributes->value for the text input, but not for the textarea.

**Comment by kevinchappell** [comment]
this appears to be resolved now
