### ISSUE TITLE
Add support for RTL languages

### ISSUE THREAD

**Issue by kevinchappell** [Draggable/formeo#66]
Translations are working great but UI needs some support for RTL languages like تونسي and فارسى.

Recommend adding a `dir` string to the language files to later be read by the editor.

**Comment by yekanchi** [comment]
is this implemented?

**Comment by kevinchappell** [comment]
@yekanchi yes, support was added however language files need to be created.
https://github.com/Draggable/formeo-i18n/tree/master/src/lang

![image](https://user-images.githubusercontent.com/1457540/103422103-98555f80-4b54-11eb-929e-ff40e0e950bf.png)
