### ISSUE TITLE
Suggestion: input grids

### ISSUE THREAD

**Issue by chrisj74** [Draggable/formeo#7]
Hi,

Appreciate you're still very early stage, but it might be worth considering input grids (a collection of inputs that in the render world allow a submitter to add multiples of the collection). This is a pretty common requirement for data capture and would be a great feature.

Thanks for all the work, looking good so far.

**Comment by kevinchappell** [comment]
I like the sound of this and think the module may already support it but could you provide some example to be sure?

Is this similar to input groups or add-ons in bootstrap or more like a rating grid?

**Comment by chrisj74** [comment]
More like a bootstrap input group. Let me give you a real example, if a form is collecting travel details it could ask you to list all the people in a group. This would involve providing name and age of each, n number. So the form would have a collection of person (constituting of 2 inputs, name and age), someone completing the form would see one collection visible, but would be able to click a button to add additional people.

It allows for an unknown number of instances to be submitted. If it was something you'd consider and it would help I could write up a much more concrete usecase.

**Comment by kevinchappell** [comment]
Ah I see, thank you for the explanation. That's a great feature I completely overlooked but actually shouldn't be too difficult to add. I think a checkbox setting in the Row and Column edit panels would be the best way to add this control, then visual feedback in the editor indicating the route or column is a collection. The generated form would have the add and remove buttons allowing the user to clone a column/row (collection) of fields or remove them.

**Comment by kevinchappell** [comment]
for reference, this has been implemented and is called Input Groups.
