### ISSUE TITLE
postion issue with Check and radio button. 

### ISSUE THREAD

**Issue by nk-nareshkumar** [Draggable/formeo#74]
Please see the attached screenshot

Effective CSS:

.formeo input[type="checkbox"] + .checkable::after, .formeo input[type="checkbox"] + .checkable::before, .formeo input[type="radio"] + .checkable::after, .formeo input[type="radio"] + .checkable::before {
left:50% 
}

![formeo drag drop form creation 4](https://cloud.githubusercontent.com/assets/2937132/25042389/4fe3264e-2135-11e7-9acb-9e40e4a7658c.png)
![formeo drag drop form creation 3](https://cloud.githubusercontent.com/assets/2937132/25042395/55f99f68-2135-11e7-978c-9a3f06264f35.png)

**Comment by kevinchappell** [comment]
~~What browser is this? I see a couple other issues that make me think it could be cached css. Can you confirm the version number [here](http://draggable.github.io/formeo/assets/formeo.min.css)?~~


nevermind im seeing it now
