### ISSUE TITLE
How do you use this with React?

### ISSUE THREAD

**Issue by shabaz-ejaz** [Draggable/formeo#92]
It's not quite clear how we should start importing this package, the only place it mentions it is here: 

> To start building forms with this module include formeo.min.js and formeo.min.css in your project and call:

There is no `formeo.min.css` file in the project and the `formeo.min.js` file is in the demo folder.

Can you please provide some clear instructions on how to get this set up as the folder structure is quite confusing.

Thanks

**Comment by shabaz-ejaz** [comment]
![2017-09-26_11h05_00](https://user-images.githubusercontent.com/29374282/30854756-8ade51b4-a2aa-11e7-950a-42d86203318e.png)

After installing through npm, there is no css file.

**Comment by kevinchappell** [comment]
styles are injected with plugin. You will need to wrap the module in a react component and initialize it in `componentDidMount` lifecycle method since formeo requires the `window` object.

**Comment by shabaz-ejaz** [comment]
I have it in a component like this:

```
import React, { Component } from 'react';
import style from '!raw!../../../node_modules/formeo/dist/formeo.min.css';
import ReactDOM from 'react-dom';

class FormeoEditor extends Component {

    componentDidMount() {
        require('formeo');

        const options = {
            container: ReactDOM.findDOMNode(this.refs.builder),
            svgSprite: '/assets/img/formeo-sprite.svg',
            i18n: {
                langsDir: '/assets/lang/',
                langs: [
                    'en-US',
                ],
            },
        };
        new window.Formeo(options);
    }

    render() {
        return (
            <div>
                <style scoped>{style}</style>
                <div ref="builder" />
            </div>
        );
    }

}
```
But I get this: 

> Unexpected '!' in '!raw!../../../node_modules/formeo/dist/formeo.min.css'. Do not use import syntax to configure webpack loaders

**Comment by kevinchappell** [comment]
Webpack 2+ you should be using `!raw-loader` but you don't need the stylesheet anymore.
In your code you can completely remove the css import and the style tag

Where did you find that example code?

**Comment by shabaz-ejaz** [comment]
If I remove the css then it wont have any styling and the icons  / colours / backgrounds wont show. Here is what it looks like at the moment: 
![2017-09-26_12h06_59](https://user-images.githubusercontent.com/29374282/30857323-35009f28-a2b3-11e7-9f8e-93a19d09dc25.png)


I found the example on the chat feature on the demo page: https://draggable.github.io/formeo/. It was actually yourself who posted it.

**Comment by shabaz-ejaz** [comment]
![2017-09-26_12h09_21](https://user-images.githubusercontent.com/29374282/30857420-8ca4f13e-a2b3-11e7-84d1-c450d0054c31.png)

**Comment by kevinchappell** [comment]
Hmm interesting. I must have written that and forgotten.

Anyhow styling looks like its working ok, only the icons are missing. In the config/options for the module you need to change `svgSprite` to point to the location of the icon sprite. This can be relative or absolute location like `https://draggable.github.io/formeo/assets/img/formeo-sprite.svg`. At some point I'll bundle icons with the module so this is not necessary.

**Comment by shabaz-ejaz** [comment]
You've sent me a link to a logo. Would it be possible to link to the sprite?

**Comment by kevinchappell** [comment]
ah, so i did. https://draggable.github.io/formeo/assets/img/formeo-sprite.svg

Also corrected original comment

**Comment by shabaz-ejaz** [comment]
Perfect. Think its all working now. Thanks

**Comment by intelligence0504** [comment]
shabaz-ejaz

Do you have the react project using formeo?
Help me.

**Comment by intelligence0504** [comment]
TypeError: window.Formeo is not a constructor

App.componentDidMount
src/App.js:21
  18 |       ],
  19 |     },
  20 |   };
> 21 |   new window.Formeo(options);
     | ^  22 |   // new Formeo({ container: '.build-form' });
  23 | }
  24 | 
View compiled

**Comment by intelligence0504** [comment]
new window.Formeo(options); is not constructor..

Help me.

**Comment by kevinchappell** [comment]
@intelligence0504 try `window.FormeoEditor`. 1.0 was accidentally released yesterday under the wrong version. Will release 0.7.19 later today the fixes the old version and publish 1.0 this evening with updated instructions.

**Comment by intelligence0504** [comment]
Thanks.
But I got other issue.

Uncaught (in promise) TypeError: Cannot read property 'firstChild' of null
    at e.empty (formeo.min.js:477)
    at l.render (formeo.min.js:7177)
    at l.init (formeo.min.js:7160)
    at formeo.min.js:7140

**Comment by intelligence0504** [comment]
npx create-react-app my-app
cd my-app
yarn add formeo  (can't install formeo module )

This is my full code (App.js)


import React, { Component } from 'react';
import './App.css';
import ReactDOM from 'react-dom';

```
class FormeoEditor extends Component {
  componentDidMount() {
      require('formeo');
      const options = {
          container: ReactDOM.findDOMNode(this.refs.builder),
          svgSprite: '/assets/img/formeo-sprite.svg',
          i18n: {
              langsDir: '/assets/lang/',
              langs: [
                  'en-US',
              ],
          },
      };
      new window.FormeoEditor(options);
  }
  render() {
      return (<div>
              <div ref="builder" />
          </div>);
               }
}
```
```
class App extends Component {
  render() {
    return (<div className="App">
      ``  <FormeoEditor/>
      </div> );
  }
}
```

export default App;

**Comment by buseodaci** [comment]
> new window.Formeo(options); is not constructor..
> 
> Help me.

This error still continus in Angular @kevinchappell

**Comment by raulsh** [comment]
I had the same error
