### ISSUE TITLE
Having "row" control in jQuery Formbuilder

### ISSUE THREAD

**Issue by MahdiRadcom** [Draggable/formeo#96]
Hi,
I want to have control grouping ability in jQuery formbuilder something like "row" control in formeo. How can I use "row" in jquery formbuilder? Is it possible to move it there? because it is like architectures are different.

**Comment by MahdiRadcom** [comment]
Thanks for your quick response. :(

**Comment by kevinchappell** [comment]
formBuilder has rows but not columns. PRs welcome.
